### ISSUE TITLE
Tin Placeholder - Ankolia Desert Central Chasm

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#101]
There are placeholders for tin ore veins in this area. Need to update to use the actual tin ore objects.

**Comment by Cablefish1** [comment]
Okay. So the problem most likely is that bronze placables doesn't exists in the module palette yet. We changed tin to bronze for some reason i can't remember. The right thing would be to "Copy Object" on the tin placeholder and then edit the variables of the bronze item.

**Comment by zunath** [comment]
So the ore veins should always be tin. Bronze is man-made by combining copper and tin together. There shouldn't be a specific bronze ore vein

**Comment by zunath** [comment]
I replaced the placeables with spawn points for tin.
