### ISSUE TITLE
Make players start with a stone shovel?

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#106]
Think that's a good idea right? Let them farm a little.

**Comment by zunath** [comment]
I'm fine with it. Maybe they get a lower tier shovel with five charges instead of the normal 10?

**Comment by Cablefish1** [comment]
I'm fine with that. It should only serve the purpose of letting players know how farming works.

**Comment by zunath** [comment]
My only concern is if we do this, we run the risk of players abusing it by making new characters. But it's a pretty minor issue I guess.
