### ISSUE TITLE
Seeds aren't dropping for trees

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#117]
Check event scripts on all tree types and make sure the local variables are set to run the correct java script.

Also make sure all tree instances which were hand-placed are updated (aka update instances)

**Comment by Cablefish1** [comment]
Updated all the tree instances. Check if that solves anything :)

**Comment by zunath** [comment]
Was an issue with the OnDeath not firing because DestroyObject was being called in the OnDamaged event. Moved all the seed generation logic to fire on the OnDamaged event instead to fix this.
