### ISSUE TITLE
Onions aren't marked as a seed

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#120]
Onions need to be marked as a seed so they can be planted.

**Comment by Cablefish1** [comment]
However I've made an item called "onion seed". Do i need to set variables on the onion plant?

**Comment by Cablefish1** [comment]
Should be fixed now. Just had to remember how to NWN.

**Comment by zunath** [comment]
I added the PLANT_ID variable to the onion item and also added it to the database. Should be good now.
