### ISSUE TITLE
Holy Shot occasionally glitches 

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#124]
From player:

Holy Shot occasionally glitches and you just.. hear the holy laser beam sound effect play continuously.

- When it glitches, it'll sometimes just.. not deal damage, too?

- It may relate to being at-a-distance from target oddly. Occuring while trying to shoot a target across a gap, possibly at the maximum range of the click ability

**Comment by Meyobrin** [comment]
* Glitched audio terminates when the target finally dies.
