### ISSUE TITLE
Respawning natural ressources

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#126]
All forageable resources that doesn't have a seed variable associated with them should respawn after six hours real time when destroyed.

Same for all Ore types, Stone Blocks and Coal.

**Comment by zunath** [comment]
You jumped from 6 hours to 10 hours :)

I'm obviously opposed to the long delay and very opposed to never respawning at all but if this is the approach we want to take and our players want it too, then I'll back down.

Doing this means every single waypoint which has been placed down for resources needs to be removed and placed with the equivalent placeable.

And to reiterate: We lose the following by not using a spawn system like NESS:

- Quick blueprint updates (need to update instances for every placeable we touch, every time we touch it)
- We lose the ability to randomize resource spawns.

**Comment by Cablefish1** [comment]
Yes. The 10 hours is just a bargaining ploy! I'm happy with 6.

As a builder i really need to look at what i'm doing. I'm getting flying resources a lot when using waypoints and loosing visual niceties. I've freescapefied old areas and created new ones a lot faster since i changed my methods.

So i'm happy loosing the quick blueprint updates. Much easier to get external builders in on it this way too.

The random ressource spawns might be a bit worse but it's still outweighed by the good things in my opinion. I still think it's less of a concern since i'm more into designing with a personal touch rather than systems placing the ressources based on some balancing algorithm.

**Comment by zunath** [comment]
I've implemented this against my better judgment...

*grumbles and walks away*
