### ISSUE TITLE
Lore info for website

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#129]
Need lore info written up for the website. Should be in the form of:

Topic Name
Description

Topic Name is the short info on the left hand side of the website.

Description is the longer, more detailed information for the topic.

**Comment by Cablefish1** [comment]
**Topic Name:** History
**Description**
Long ago the world suffered a catastrophe of epic proportions. Not much is known about it. No one who lived in the world before is around to tell about it.  All that's known is that large quanitites of magic was involved and that the world was shattered right down to the very fabric of reality. The advanced civilization that once ruled is all but gone leaving nothing behind except ruins and on a rare occasion strange artifacts and relics.

**Comment by Cablefish1** [comment]
**Topic Name:** Magic
**Description**
Magic is a natural force in Freescape. It was integral in shattering the world and it can be found as a natural force still at work keeping areas unreal and reality broken. Animals and other creatures gets twisted into strange and unnatural forms. Inanimate objects gains life of sorts and forces like gravity can even stop working.

Some places magic has even condensed into crystal form. These crystals of so caled "magicite" is sought after by wizards seeking to understand it and unlock its potential. Magicite can be found in different forms and shapes and have various exotic and sometimes dangerous properties for those seeking to tame it's power. These crystals are mostly found where the local concentrations of magic is the strongest.

**Comment by Cablefish1** [comment]
**Topic Name:** Rifts in reality
**Description**
When the catastrophe happened the world shattered into fragments of reality that went tumbling through the multiverse colliding with other worlds and realities. Most of the world is slowly coalescing back into a shape that is at least real enough for stuff to live there. But the fragments didn't all come back in the right places. The world got shattered to such an extend that pieces of the puzzle of the world got swapped out with pieces from other realities. Creatures, people, objects and even ideas from other places are slowly leaking into the world through the cracks in the curtain of reality.

**Comment by zunath** [comment]
Added to the website.
