### ISSUE TITLE
Seeds PLANT_ID list

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#131]
- [x] Potato PLANT_ID 51 potato_plant lvl 5
- [x] Leek PLANT_ID 52 plant_leek lvl 5
- [x] Grape Vine PLANT_ID 53 plant_grape lvl 10
- [x] PLANT_ID 54 plant_bellpepper lvl 5

**Comment by zunath** [comment]
Can you get me the forage levels of these plants? Will help save me time when determining what farming level to make them.

**Comment by Cablefish1** [comment]
Done

**Comment by zunath** [comment]
The Potato item (not seeds) have a PLANT_ID of 43 on them. Either need to remove this or set it to 51.

Both Leek and Leek Seeds can be planted - is this intended?

Bell Pepper (not seeds) has a PLANT_ID of 43 as well. Need to know what the intention is here - remove or set to 54.

**Comment by Cablefish1** [comment]
Everything that has a seperate seed item is not supposed to be planted. This is from my sloppy "Copy Item" proces. It will be fixed shortly.

**Comment by zunath** [comment]
Ok. I'll let you edit the module since I'm on a crappy connection lol. I've added them to the DB but haven't deployed to the server yet. Probably do that in the morning. Might get errors until then.

**Comment by zunath** [comment]
Actually I just deployed the DB changes so as soon as you fix the module problems just close this ticket.

**Comment by Cablefish1** [comment]
Should be all fixed now :)
