### ISSUE TITLE
Ankolia Desert - Central Chasm: Placeholder boulder

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#18]
There's a placeholder boulder in Ankolia Desert - Central Chasm. It's named "Climping Placeholder CR15".

No idea what this is intended to be. But we need to replace it with something else.

**Comment by zunath** [comment]
I can't come up with a way to implement this without it violating our rule of "no spammable skills". 

Would we be able to get away with pure attribute DC checks against Dexterity or something along those lines?

The only other thing I can think of is to have a single Mobility skill (or something similarly named) which only gains XP from taking actions - but the XP gains are time-locked. It's not really ideal in my mind but if we need to have it, that's one way to do it.

**Comment by Cablefish1** [comment]
Sure thing. Perfectly happy with a pure attribute DC checks against stat or stats combo. Thats also how the movements skills old freescape used work. 

What could improve the module would be these three movement skills:
Climb: DC against str+dex
Swim: DC against str+con
Jump: DC against str.

The above link has some rudimentary animations too that you can steal :)

**Comment by zunath** [comment]
Cable added in the system he linked... no custom code needed at the moment for this feature.
