### ISSUE TITLE
Figure out some mechanic regarding poison and disease

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#40]
Stat reduction are usually remedied through resting however Freescape currently has no resting so we need to figure out some alternative.

**Comment by zunath** [comment]
I have a custom effect system in place for this sort of thing. We just need to hook the effects up to use it. I assume these are coming from enemies?

**Comment by zunath** [comment]
I've made the Purify spell remove Poison/Disease. I think a first aid item is in order too.

**Comment by zunath** [comment]
I've added treatment kits for first aid which will remove these effects.
