### ISSUE TITLE
Exploration trigger throwing exception

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#44]
One of the exploration triggers with the following text is misconfigured:

Before you stands an ancient building. Though time and whatever plagues these lands have taken its toll it appear to be safe to enter.

The text is in place of the java script variable. This needs to be fixed so that it'll display properly in game.

**Comment by Cablefish1** [comment]
Should be fixed. However i'm not sure i'm feeling the love from the exploration triggers in game. Not sure they're working right. Must investigate more...

**Comment by zunath** [comment]
Didn't run into any errors in-game during testing so I think it's probably good. If not we can open another ticket.
