### ISSUE TITLE
Make mobility objects plot

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#68]
Players can damage the objects used for mobility actions (jumping, climbing, etc.). These need to all be set to Plot

**Comment by taelon875** [comment]
Also need to be check to make sure they work both ways to avoid getting stuck.

**Comment by zunath** [comment]
I updated the blueprints for these and updated one of the starter areas to make the existing ones plot. However, I was hesitant to update instances because I don't know if each one has to be customized. I was worried about removing changes Cable made.

Let me know if it's safe to update instances or if you're going to update the existing areas to make these plot @Cablefish1

**Comment by zunath** [comment]
I updated all instances based on Cable's feedback in Discord. Open a new ticket if we've still got problems.
