### ISSUE TITLE
Increase price of perks

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#78]
I think the perk prices are too low now. Players have a maximum of 505 SP (500 from skill ups, and 5 they get for free).

The current price to learn all perks is 864. Granted this will increase as we add more perks, but I think we may want to increase the price by 1, 2 or 3 SP across the board.

If we keep it as-is, the total price of everything will be 864.
If we increase by 1, the total price of everything will be 1233.
If we increase by 2, the total price of everything will be 1602.
If we increase by 3, the total price of everything will be 1971.

It's definitely a balancing act of allowing players to customize their characters while at the same time keeping them from being a master of everything.

I won't take any action until we've had time to discuss, But I'm definitely thinking of a +2 or +3 increase personally.

**Comment by taelon875** [comment]
Depending on how easy it is to undo/change A increase by 2 is not the worst for now, but as you ad more perks I think a increase of 1 may become more viable... I wouldn't be too upset if it were increased.

**Comment by zunath** [comment]
I decided to bump it up only by 1 for now. We'll see how that goes and if we need to we can bump it again. I just don't want to gate progress too much. I keep adding perks too, so the numbers keep getting higher.
