### ISSUE TITLE
Character Backgrounds, AKA "Professions"

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#79]
CZS has a Profession system which allows players to pick one character background on module entry. This background gives them one temporary buff (which will be outpaced by crafting or other activities) and one permanent buff that you can't get otherwise.

I think it helps new players out a lot because they aren't starting with basically nothing. It also gives them a starting place for their character background.

It might be a good idea to implement something like this to Freescape. Some ideas I had:

**Amateur Weaponsmith**
Temp: +1 to Weapon Blueprints perk
Perm: +1 level to all weaponsmith crafting checks

**Amateur Armorsmith**
Temp: +1 to Armor Blueprints perk
Perm: +1 level to all armorsmith crafting checks

**Knight**
Temp: Tier 1-equivalent armor
Perm: +10 HP bonus

**Wizard**
Temp: +1 to Fire Blast perk
Perm: +10 Mana bonus

**Cleric**
Temp: +1 to Recover perk
Perm: +10 Mana bonus

**Archer**
Temp: Tier 1-equivalent bow, basic arrows 
Perm: +1 DEX, +1 WIS

**Crossbowman**
Temp: Tier 1-equivalent crossbow, basic bolts
Perm: +1 DEX, +1 WIS

And so on... Open to other ideas.

**Comment by Cablefish1** [comment]
Oh that is so cool. Very in thread with the fact that could come from anywhere with any background. I like it a lot! And i'd like to write the dialogue where this is chosen in order to give the player a neat intro to the world too :)

**Comment by zunath** [comment]
Sure! If you want to write them up on this ticket feel free. When you finish I'll get to implementing them.

**Comment by Cablefish1** [comment]
I'll get it done at some point this week. Feel free to add in something rudimentary if you want to test it before that.
