### ISSUE TITLE
Coal Cave bugs

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#85]
The Coal Cave Areas has the following issues:
1: Area transition isn't working right.
2: The area needs the area_heartbeat script in events.

**Comment by zunath** [comment]
The tags on your triggers are too long. I think transitions have a max of 32 characters. I'm shortening them and fixing it now.

NESS appears to be working? I got a fire beetle to spawn on me during testing.

**Comment by zunath** [comment]
The NESS waypoint name replacement doesn't work unless it's running java, so that's why it doesn't work locally. But it appears to be spawning right now?

Fixed the transition too.
