### ISSUE TITLE
Maple Trees - Ankolia Desert

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#9]
The maple trees in Ankolia Desert aren't using the proper scripts. Plus the entire tree is usable, instead of the invisible object. Might be that there are multiple maple tree placeables in the module.

I noticed they have maple syrup - we should probably look into acquiring that using the proper tools and integrate it into the existing resource gathering scripts.

**Comment by Cablefish1** [comment]
Maple trees from old freescape BEGONE!

(like literally. They are gone and replaced with newer more fancy stuff)
